


import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Melih
 */
public class Hardware extends MainFrame {



    /**
     * Creates new form Hardware
     */
    public Hardware() {

        super();
        initComponents();
        updateTable();
        setLocationRelativeTo(null);
        updateTable();
        updateCombobox();

        DateFormat onlyDate = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        ariza_tarihi_giris.setText(onlyDate.format(date));
        ariza_tarihi_giris.setText(ariza_tarihi_giris.getText());
        ariza_tarihi_giris.setEditable(false);
        ariza_tarihi_giris.setBackground(Color.gray);

        jTextArea2.setEditable(false);

    }

    private void updateTable() {

        String updateQuery = "select * from donanım";

        try {

            prepared = connect.prepareStatement(updateQuery);
            resultSet = prepared.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(resultSet));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }

    private void updateCombobox() {

        String sql = "select * from donanım";
        try {

            prepared = connect.prepareStatement(sql);
            resultSet = prepared.executeQuery();

            while (resultSet.next()) {
                jComboBox1.addItem(resultSet.getString("bildirim_sicili"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        seri_no = new javax.swing.JLabel();
        merkez_adi = new javax.swing.JLabel();
        sube_adi = new javax.swing.JLabel();
        cihaz_modeli = new javax.swing.JLabel();
        bildirim_sicili = new javax.swing.JLabel();
        ariza_aciklamasi = new javax.swing.JLabel();
        ariza_tarihi = new javax.swing.JLabel();
        seri_no_giris = new javax.swing.JTextField();
        cihaz_modeli_giris = new javax.swing.JTextField();
        bildirim_sicili_giris = new javax.swing.JTextField();
        ariza_acıklamasi_giris = new javax.swing.JTextField();
        ariza_tarihi_giris = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        hardware_add_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        merkez_combobox = new javax.swing.JComboBox<>();
        şube_combobox = new javax.swing.JComboBox<>();
        bilgi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        back_button2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        güncelle_button = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        elle_degistir = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        search_hardware = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Herhangi bir veriyi güncellemek için aşağıdaki kutudan üstüne tıklayın.\nÜstüne tıkladıktan sonra bildirim numarasının sağ kutuda belirmesini\nbekleyin. Numara belirdikten sonra üstteki kutular otomatik dolacaktır.\nVerileri değiştirin ve güncelleye basın.");
        jScrollPane2.setViewportView(jTextArea1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Donanım Problemleri");

        seri_no.setText("Seri No:");

        merkez_adi.setText("Merkez Adı:");

        sube_adi.setText("Şube Adı:");

        cihaz_modeli.setText("Cihaz Modeli:");

        bildirim_sicili.setText("Bildirim Sicili:");

        ariza_aciklamasi.setText("Arıza Açıklaması:");

        ariza_tarihi.setText("Arıza Tarihi:");

        seri_no_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seri_no_girisActionPerformed(evt);
            }
        });

        cihaz_modeli_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cihaz_modeli_girisActionPerformed(evt);
            }
        });

        bildirim_sicili_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bildirim_sicili_girisActionPerformed(evt);
            }
        });
        bildirim_sicili_giris.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bildirim_sicili_girisKeyTyped(evt);
            }
        });

        ariza_tarihi_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ariza_tarihi_girisActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Merkez Adı", "Şube Adı", "Seri No", "Cihaz Modeli", "Bildirim Sicili", "Arıza Açıklaması", "Arıza Tarihi"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        hardware_add_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hardware_add_button.setForeground(new java.awt.Color(0, 153, 255));
        hardware_add_button.setText("Ekle");
        hardware_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardware_add_buttonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Kaldır");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        merkez_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AKÇAABAT", "ÇAYKARA", "DÜZKÖY", "FATİH", "MAÇKA", "OF", "SÜRMENE", "TONYA", "TRABZON", "YOMRA" }));
        merkez_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merkez_comboboxActionPerformed(evt);
            }
        });

        şube_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                şube_comboboxActionPerformed(evt);
            }
        });

        bilgi.setText("Herhangi bir veriyi silmek için seri numarasını kullanabilirsiniz.");

        jLabel3.setText("---------------------------------------------------------------------------------------------------------------------------");

        jLabel4.setText("---------------------------------------------------------------------------------------------------------------------------");

        back_button2.setText("Geri Dön");
        back_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_button2ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Herhangi bir veriyi güncellemek için aşağıdaki kutudan üstüne tıklayın.\nÜstüne tıkladıktan sonra bildirim numarasının sağ kutuda belirmesini\nbekleyin. Numara belirdikten sonra üstteki kutular otomatik dolacaktır.\nVerileri değiştirin ve güncelleye basın.");
        jScrollPane3.setViewportView(jTextArea2);

        güncelle_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        güncelle_button.setForeground(new java.awt.Color(102, 102, 255));
        güncelle_button.setText("Güncelle");
        güncelle_button.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                güncelle_buttonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        güncelle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelle_buttonActionPerformed(evt);
            }
        });

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        elle_degistir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        elle_degistir.setForeground(new java.awt.Color(0, 204, 0));
        elle_degistir.setText("Elle Değiştir");
        elle_degistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elle_degistirActionPerformed(evt);
            }
        });

        search_hardware.setText("Ara");
        search_hardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_hardwareActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("Donanımsal hatayı seri numarasını kullanarak bulabilirsiniz.");

        jLabel12.setFont(new java.awt.Font("Edwardian Script ITC", 0, 14)); // NOI18N
        jLabel12.setText("Ihsan Melih Sisman Tarafından");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bildirim_sicili)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bildirim_sicili_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ariza_aciklamasi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ariza_acıklamasi_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(seri_no)
                                                    .addComponent(cihaz_modeli)
                                                    .addComponent(merkez_adi)
                                                    .addComponent(sube_adi))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cihaz_modeli_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(seri_no_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(şube_combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(merkez_combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE))
                                                    .addComponent(jLabel1)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ariza_tarihi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ariza_tarihi_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hardware_add_button)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(elle_degistir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(search_hardware))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back_button2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(güncelle_button))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(bilgi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(back_button2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merkez_adi)
                    .addComponent(merkez_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sube_adi)
                    .addComponent(şube_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seri_no_giris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seri_no, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cihaz_modeli)
                    .addComponent(cihaz_modeli_giris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bildirim_sicili)
                    .addComponent(bildirim_sicili_giris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ariza_aciklamasi)
                    .addComponent(ariza_acıklamasi_giris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ariza_tarihi)
                    .addComponent(ariza_tarihi_giris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elle_degistir))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(hardware_add_button)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_hardware))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(bilgi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(güncelle_button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hardware_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardware_add_buttonActionPerformed
        String insertQuery = "INSERT INTO donanım(Merkez_Adı,Şube_Adı,Seri_No,Cihaz_Modeli,Bildirim_Sicili,Arıza_Açıklaması,Arıza_Tarihi) values(?,?,?,?,?,?,?::date)";
        try {

            prepared = connect.prepareStatement(insertQuery);

            prepared.setString(1, merkez_combobox.getSelectedItem().toString());
            prepared.setString(2, şube_combobox.getSelectedItem().toString());
            prepared.setString(3, seri_no_giris.getText());
            prepared.setString(4, cihaz_modeli_giris.getText());
            prepared.setInt(5, Integer.parseInt(bildirim_sicili_giris.getText()));
            prepared.setString(6, ariza_acıklamasi_giris.getText());
            prepared.setString(7, ariza_tarihi_giris.getText());

            if (seri_no_giris.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Seri numarası boş bırakılamaz.");
                return;
            } else if (cihaz_modeli_giris.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Cihaz modeli alanı boş bırakılamaz.");
                return;
            } else if (bildirim_sicili_giris.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Bildirim sicili alanı boş bırakılamaz.");
                return;
            } else if (ariza_acıklamasi_giris.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Arıza açıklaması boş bırakılamaz.");
                return;
            }

            prepared.execute();

            JOptionPane.showMessageDialog(null, "Veritabanına başarıyla eklendi.");

            updateTable();
            updateCombobox();;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_hardware_add_buttonActionPerformed

    private void seri_no_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seri_no_girisActionPerformed

    }//GEN-LAST:event_seri_no_girisActionPerformed

    private void cihaz_modeli_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cihaz_modeli_girisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cihaz_modeli_girisActionPerformed

    private void merkez_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merkez_comboboxActionPerformed

        if (merkez_combobox.getSelectedItem().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Merkez listesi boş bırakılamaz.");
            şube_combobox.removeAllItems();
        } else if (merkez_combobox.getSelectedItem().equals("AKÇAABAT")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("DERECİK");
            şube_combobox.addItem("İLKADIM");
            şube_combobox.addItem("KAVAKLI");
            şube_combobox.addItem("SÖĞÜTLÜ");
            şube_combobox.addItem("YAYLACIK");
            şube_combobox.addItem("YILDIZLI");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_combobox.getSelectedItem().equals("ÇAYKARA")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("UZUNGÖL");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_combobox.getSelectedItem().equals("DÜZKÖY")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("ÇAYIRBAĞI");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_combobox.getSelectedItem().equals("DÜZKÖY")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("ÇAYIRBAĞI");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_combobox.getSelectedItem().equals("FATİH")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("BEŞİRLİ");
            şube_combobox.addItem("ÇATAK");
            şube_combobox.addItem("ERDOĞDU");
            şube_combobox.addItem("HÜKÜMET KONAĞI");
            şube_combobox.addItem("KARŞIYAKA");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_combobox.getSelectedItem().equals("MAÇKA")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("ESİROĞLU");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_combobox.getSelectedItem().equals("OF")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("GÜRPINAR");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_combobox.getSelectedItem().equals("SÜRMENE")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("ÇAMBURNU");
            şube_combobox.addItem("ÇARŞI");
            şube_combobox.addItem("KÖPRÜBAŞI");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_combobox.getSelectedItem().equals("TONYA")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("İSKENDERLİ");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_combobox.getSelectedItem().equals("TRABZON")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("ÇAĞLAYAN");
            şube_combobox.addItem("ÇUKURÇAYIR");
            şube_combobox.addItem("DEĞİRMENDERE");
            şube_combobox.addItem("K.T.Ü");
            şube_combobox.addItem("ORTAHİSAR KAYMAKAMLIĞI");
            şube_combobox.addItem("PARK");
            şube_combobox.addItem("PELİTLİ");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_combobox.getSelectedItem().equals("YOMRA")) {
            şube_combobox.removeAllItems();
            şube_combobox.addItem("");
            şube_combobox.addItem("ADLİYE SARAYI");
            şube_combobox.addItem("KAŞÜSTÜ");
        }
    }//GEN-LAST:event_merkez_comboboxActionPerformed

    private void şube_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_şube_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_şube_comboboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!table.getSelectionModel().isSelectionEmpty()) {
            int row = table.getSelectedRow();
            String cell = table.getModel().getValueAt(row, 4).toString();
            String sql = "Delete FROM donanım where bildirim_sicili = " + cell;

            try {

                prepared = connect.prepareStatement(sql);
                prepared.execute();

                JOptionPane.showMessageDialog(null, "Başarıyla silindi.");
                updateTable();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kaldırmak için bir kolon seçin.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bildirim_sicili_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bildirim_sicili_girisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bildirim_sicili_girisActionPerformed

    private void back_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_button2ActionPerformed

        dispose();
        HomePage homepage = new HomePage();
        homepage.show();

    }//GEN-LAST:event_back_button2ActionPerformed

    private void güncelle_buttonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_güncelle_buttonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_güncelle_buttonAncestorAdded

    private void güncelle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelle_buttonActionPerformed

        try {

            if (table.getSelectedRowCount() == 1) {
                //if single row is selected then update
                String updateQuery = "Update Donanım set "
                        + " merkez_adı = '" + merkez_combobox.getSelectedItem() + "',"
                        + " Şube_adı = '" + şube_combobox.getSelectedItem() + "',"
                        + " Seri_No = '" + seri_no_giris.getText() + "',"
                        + " cihaz_modeli = '" + cihaz_modeli_giris.getText() + "',"
                        + " bildirim_sicili = '" + bildirim_sicili_giris.getText() + "',"
                        + " arıza_açıklaması = '" + ariza_acıklamasi_giris.getText() + "',"
                        + " arıza_tarihi = '" + ariza_tarihi_giris.getText() + "'"
                        + " where bildirim_sicili = " + jComboBox1.getSelectedItem().toString();

                prepared = connect.prepareStatement(updateQuery);
                prepared.execute();
                JOptionPane.showMessageDialog(this, "Başarıyla güncellendi.");
                updateTable();
                updateCombobox();

            } else {
                if (table.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "Tablo boş.");
                } else {
                    JOptionPane.showMessageDialog(this, "Lütfen sadece bir tane veri seçin..");
                }
                connect.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_güncelle_buttonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox1.setEnabled(false);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void elle_degistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elle_degistirActionPerformed
        DateFormat onlyDate = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        ariza_tarihi_giris.setText(onlyDate.format(date));
        ariza_tarihi_giris.setText(ariza_tarihi_giris.getText());
        ariza_tarihi_giris.setEditable(true);
        ariza_tarihi_giris.setBackground(Color.white);

    }//GEN-LAST:event_elle_degistirActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.getSelectedRow();
        String cell = table.getModel().getValueAt(row, 4).toString();
        String sql = "select * FROM donanım where bildirim_sicili =" + cell;
        try {

            prepared = connect.prepareStatement(sql);
            resultSet = prepared.executeQuery();
            if (resultSet.next()) {
                jComboBox1.setSelectedItem(resultSet.getString("bildirim_sicili"));
                merkez_combobox.setSelectedItem(resultSet.getString("merkez_adı"));
                şube_combobox.setSelectedItem(resultSet.getString("Şube_adı"));
                seri_no_giris.setText(resultSet.getString("seri_no"));
                cihaz_modeli_giris.setText(resultSet.getString("cihaz_modeli"));
                bildirim_sicili_giris.setText(resultSet.getString("bildirim_sicili"));
                ariza_acıklamasi_giris.setText(resultSet.getString("arıza_açıklaması"));
                ariza_tarihi_giris.setText(resultSet.getString("arıza_tarihi"));

            }
            updateCombobox();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked


    }//GEN-LAST:event_jButton2MouseClicked

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        /*  String item = (String) jComboBox1.getSelectedItem();
        String sql = "select * FROM donanım where bildirim_sicili = ?";

        try {
            
            prepared = connect.prepareStatement(sql);
            prepared.setString(1, item);
            resultSet = prepared.executeQuery();

            if (resultSet.next()) {
                merkez_combobox.setSelectedItem((resultSet.getString("merkez_adı")));
                şube_combobox.setSelectedItem((resultSet.getString("Şube_adı")));
                seri_no_giris.setText(resultSet.getString("seri_no"));
                cihaz_modeli_giris.setText(resultSet.getString("cihaz_modeli"));
                bildirim_sicili_giris.setText(resultSet.getString("bildirim_sicili"));
                ariza_acıklamasi_giris.setText(resultSet.getString("arıza_açıklaması"));
                ariza_tarihi_giris.setText(resultSet.getString("arıza_tarihi"));
                
            }
        } catch (Exception e) {
        }

         */
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void search_hardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_hardwareActionPerformed

        try {

            String sql = "select * from donanım where seri_no = ?";

            prepared = connect.prepareStatement(sql);
            prepared.setString(1, jTextField1.getText());

            resultSet = prepared.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(resultSet));
            if (resultSet.next()) {

                jComboBox1.setSelectedItem(resultSet.getString("bildirim_sicili"));
                merkez_combobox.setSelectedItem(resultSet.getString("merkez_adı"));
                şube_combobox.setSelectedItem(resultSet.getString("Şube_adı"));
                seri_no_giris.setText(resultSet.getString("seri_no"));
                cihaz_modeli_giris.setText(resultSet.getString("cihaz_modeli"));
                bildirim_sicili_giris.setText(resultSet.getString("bildirim_sicili"));
                ariza_acıklamasi_giris.setText(resultSet.getString("arıza_açıklaması"));
                ariza_tarihi_giris.setText(resultSet.getString("arıza_tarihi"));

            }
            if (jTextField1.getText().isEmpty()) {
                updateTable();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        updateCombobox();


    }//GEN-LAST:event_search_hardwareActionPerformed

    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tableKeyReleased

    private void ariza_tarihi_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ariza_tarihi_girisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ariza_tarihi_girisActionPerformed

    private void bildirim_sicili_girisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bildirim_sicili_girisKeyTyped

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE) {
            getToolkit().beep();
            evt.consume();
        }


    }//GEN-LAST:event_bildirim_sicili_girisKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hardware().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ariza_aciklamasi;
    private javax.swing.JTextField ariza_acıklamasi_giris;
    private javax.swing.JLabel ariza_tarihi;
    private javax.swing.JTextField ariza_tarihi_giris;
    private javax.swing.JButton back_button2;
    private javax.swing.JLabel bildirim_sicili;
    private javax.swing.JTextField bildirim_sicili_giris;
    private javax.swing.JLabel bilgi;
    private javax.swing.JLabel cihaz_modeli;
    private javax.swing.JTextField cihaz_modeli_giris;
    private javax.swing.JButton elle_degistir;
    private javax.swing.JButton güncelle_button;
    private javax.swing.JButton hardware_add_button;
    private javax.swing.JButton jButton2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel merkez_adi;
    private javax.swing.JComboBox<String> merkez_combobox;
    private javax.swing.JButton search_hardware;
    private javax.swing.JLabel seri_no;
    private javax.swing.JTextField seri_no_giris;
    private javax.swing.JLabel sube_adi;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> şube_combobox;
    // End of variables declaration//GEN-END:variables
}
