


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Melih
 */
public class login5 extends MainFrame {

    /**
     * Creates new form login
     */
    public login5() {

        super();
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Password_Checker = new javax.swing.JCheckBox();
        J_Username_Label = new javax.swing.JLabel();
        J_Password_Label = new javax.swing.JLabel();
        jtext_username = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        j_password = new javax.swing.JPasswordField();
        reset_button = new javax.swing.JButton();
        sup_sentence = new javax.swing.JLabel();
        sub_sentence = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Password_Checker.setForeground(new java.awt.Color(204, 0, 51));
        Password_Checker.setText("Şifreyi Kontrol Et");
        Password_Checker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_CheckerActionPerformed(evt);
            }
        });

        J_Username_Label.setText("Kullanıcı Adı:");

        J_Password_Label.setText("Şifre:");

        jtext_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_usernameActionPerformed(evt);
            }
        });

        login_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_button.setForeground(new java.awt.Color(0, 204, 204));
        login_button.setText("Giriş Yap");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        login_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_buttonKeyPressed(evt);
            }
        });

        j_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                j_passwordKeyPressed(evt);
            }
        });

        reset_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset_button.setForeground(new java.awt.Color(255, 0, 51));
        reset_button.setText("Sıfırla");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });

        sup_sentence.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        sup_sentence.setForeground(new java.awt.Color(204, 204, 0));
        sup_sentence.setText("Ptt.");

        sub_sentence.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        sub_sentence.setForeground(new java.awt.Color(255, 0, 0));
        sub_sentence.setText("Error Pathfinder Tool");

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 0, 14)); // NOI18N
        jLabel1.setText("Ihsan Melih Sisman Tarafından");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub_sentence)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(sup_sentence, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(J_Password_Label)
                            .addComponent(J_Username_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j_password)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(login_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reset_button))
                            .addComponent(jtext_username))
                        .addGap(18, 18, 18)
                        .addComponent(Password_Checker)))
                .addGap(71, 77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(sup_sentence, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub_sentence, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtext_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J_Username_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J_Password_Label)
                    .addComponent(Password_Checker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_button)
                    .addComponent(reset_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtext_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_usernameActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed

        //    String username = "Melih";
        //   String password = "1234";
        //   if (jtext_username.getText().equals(username) && j_passoword.getText().equals(password)) {
        //      JOptionPane.showMessageDialog(null, "Login Successfully");
        //   } else {
        //      JOptionPane.showMessageDialog(null, "username or password are not correct");
        //  }
        try {

            Class.forName("org.postgresql.Driver");

            String url = "jdbc:postgresql://localhost/postgres?user=postgres&password=Seyda1972.";
            connect = DriverManager.getConnection(url);
            String sql = "select * from login_info where username = ? and password = ?";
            PreparedStatement prepared = connect.prepareStatement(sql);
            prepared.setString(1, jtext_username.getText());
            prepared.setString(2, j_password.getText());
            resultSet = prepared.executeQuery();

            System.out.println("Java JDBC PostgreSQL Example");
            System.out.println("Connected to PostgreSQL database!");

            if (resultSet.next()) {
                dispose();
                HomePage hpage = new HomePage();
                hpage.show();
            } else {
                JOptionPane.showMessageDialog(this, "Username or password are wrong.");
                jtext_username.setText("");
                j_password.setText("");
            }
            connect.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_login_buttonActionPerformed

    private void Password_CheckerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_CheckerActionPerformed
        if (Password_Checker.isSelected()) {
            j_password.setEchoChar((char) 0);
        } else {
            j_password.setEchoChar('*');
        }
    }//GEN-LAST:event_Password_CheckerActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        jtext_username.setText("");
        j_password.setText("");
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void login_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_buttonKeyPressed

    }//GEN-LAST:event_login_buttonKeyPressed

    private void j_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {

                Class.forName("org.postgresql.Driver");
                String url = "jdbc:postgresql://localhost/postgres?user=postgres&password=Seyda1972.";
                connect = DriverManager.getConnection(url);

                String sql = "select * from login_info where username = ? and password = ?";
                PreparedStatement prepared = connect.prepareStatement(sql);
                prepared.setString(1, jtext_username.getText());
                prepared.setString(2, j_password.getText());
                resultSet = prepared.executeQuery();

                System.out.println("Java JDBC PostgreSQL Example");
                System.out.println("Connected to PostgreSQL database!");

                if (resultSet.next()) {
                    dispose();
                    HomePage hpage = new HomePage();
                    hpage.show();
                } else {
                    JOptionPane.showMessageDialog(this, "Username or password are wrong.");
                    jtext_username.setText("");
                    j_password.setText("");
                }
                connect.close();

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_j_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login5().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J_Password_Label;
    private javax.swing.JLabel J_Username_Label;
    private javax.swing.JCheckBox Password_Checker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField j_password;
    private javax.swing.JTextField jtext_username;
    private javax.swing.JButton login_button;
    private javax.swing.JButton reset_button;
    private javax.swing.JLabel sub_sentence;
    private javax.swing.JLabel sup_sentence;
    // End of variables declaration//GEN-END:variables
}
