

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Melih
 */
public class Software extends MainFrame {

    /**
     * Creates new form Software
     */
    public Software() {

        super();

        initComponents();
        setLocationRelativeTo(null);
        updateTable();
        updateCombobox();

        DateFormat onlyDate = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        ariza_tarihi_yazılım.setText(onlyDate.format(date));
        ariza_tarihi_yazılım.setText(ariza_tarihi_yazılım.getText());
        ariza_tarihi_yazılım.setEditable(false);
        ariza_tarihi_yazılım.setBackground(Color.gray);

        jTextArea1.setEditable(false);

    }

    private void updateTable() {

        String updateQuery = "select * from yazılım";

        try {

            prepared = connect.prepareStatement(updateQuery);
            resultSet = prepared.executeQuery();
            table2.setModel(DbUtils.resultSetToTableModel(resultSet));
            updateCombobox();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }

    private void updateCombobox() {

        String sql = "select * from yazılım";
        try {

            prepared = connect.prepareStatement(sql);
            resultSet = prepared.executeQuery();

            while (resultSet.next()) {
                jComboBox1.addItem(resultSet.getString("bildirim_sicili"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        merkez_adi = new javax.swing.JComboBox<>();
        sube_adi = new javax.swing.JComboBox<>();
        software_merkez_adı_bilgi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        müdahale_edilen_program = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bildirim_sicili_giris_yazılım = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        arıza_aciklamasi_yazılım = new javax.swing.JTextField();
        ariza_tarihi_yazılım = new javax.swing.JTextField();
        Ekle_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Kaldır_button = new javax.swing.JButton();
        elle_degistir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        güncelle_button = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        search_hardware = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Yazılım Problemleri");

        merkez_adi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AKÇAABAT", "ÇAYKARA", "DÜZKÖY", "FATİH", "MAÇKA", "OF", "SÜRMENE", "TONYA", "TRABZON", "YOMRA" }));
        merkez_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merkez_adiActionPerformed(evt);
            }
        });

        software_merkez_adı_bilgi.setText("Merkez Adı:");

        jLabel3.setText("Şube Adı:");

        jLabel4.setText("Müdahale Edilen Program:");

        jLabel5.setText("Bildirim Sicili:");

        bildirim_sicili_giris_yazılım.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bildirim_sicili_giris_yazılımKeyTyped(evt);
            }
        });

        jLabel6.setText("Arıza Açıklaması:");

        jLabel7.setText("Arıza Tarihi:");

        arıza_aciklamasi_yazılım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arıza_aciklamasi_yazılımActionPerformed(evt);
            }
        });

        Ekle_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ekle_button.setForeground(new java.awt.Color(0, 204, 204));
        Ekle_button.setText("Ekle");
        Ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ekle_buttonActionPerformed(evt);
            }
        });

        back_button.setText("Geri Dön");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Merkez Adı", "Şube Adı", "Müdahale Edilen Program", "Bildirim Sicili", "Arıza Açıklaması", "Arıza Tarihi"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table2);

        jLabel2.setText("-------------------------------------------------------------------------------------------------------------------------------");

        jLabel8.setText("-------------------------------------------------------------------------------------------------------------------------------");

        Kaldır_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Kaldır_button.setForeground(new java.awt.Color(255, 0, 0));
        Kaldır_button.setText("Kaldır");
        Kaldır_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kaldır_buttonActionPerformed(evt);
            }
        });

        elle_degistir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        elle_degistir.setForeground(new java.awt.Color(0, 204, 0));
        elle_degistir.setText("Elle Değiştir");
        elle_degistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elle_degistirActionPerformed(evt);
            }
        });

        jLabel9.setText(" Herhangi bir veriyi silmek için üstüne tıklayın ve kaldır butonuna basın.");

        güncelle_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        güncelle_button.setForeground(new java.awt.Color(102, 102, 255));
        güncelle_button.setText("Güncelle");
        güncelle_button.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                güncelle_buttonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        güncelle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelle_buttonActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel10.setText("-------------------------------------------------------------------------------------------------------------------------------");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Herhangi bir veriyi güncellemek için aşağıdaki kutudan üstüne tıklayın.\nÜstüne tıkladıktan sonra bildirim numarasının sağ kutuda belirmesini\nbekleyin. Numara belirdikten sonra üstteki kutular otomatik dolacaktır.\nVerileri değiştirin ve güncelleye basın.");
        jScrollPane2.setViewportView(jTextArea1);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setText("Yazılımsal hatayı program adını kullanarak bulabilirsiniz.");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        search_hardware.setText("Ara");
        search_hardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_hardwareActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Edwardian Script ITC", 0, 14)); // NOI18N
        jLabel12.setText("Ihsan Melih Sisman Tarafından");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(back_button)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(güncelle_button)))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(search_hardware)))
                                        .addGap(42, 42, 42)
                                        .addComponent(Ekle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(software_merkez_adı_bilgi)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arıza_aciklamasi_yazılım, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ariza_tarihi_yazılım, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bildirim_sicili_giris_yazılım, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(müdahale_edilen_program, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sube_adi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(merkez_adi, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(elle_degistir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kaldır_button)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(software_merkez_adı_bilgi)
                    .addComponent(merkez_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sube_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(müdahale_edilen_program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bildirim_sicili_giris_yazılım, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(arıza_aciklamasi_yazılım, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ariza_tarihi_yazılım, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elle_degistir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_hardware)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ekle_button)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kaldır_button)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(güncelle_button))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void merkez_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merkez_adiActionPerformed

        //////////////////////////////////////////////////////////////////////////////// 
        if (merkez_adi.getSelectedItem().equals(" ")) {
            JOptionPane.showMessageDialog(null, "Merkez listesi boş bırakılamaz.");
            sube_adi.removeAllItems();
        } else if (merkez_adi.getSelectedItem().equals("AKÇAABAT")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("DERECİK");
            sube_adi.addItem("İLKADIM");
            sube_adi.addItem("KAVAKLI");
            sube_adi.addItem("SÖĞÜTLÜ");
            sube_adi.addItem("YAYLACIK");
            sube_adi.addItem("YILDIZLI");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_adi.getSelectedItem().equals("ÇAYKARA")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("UZUNGÖL");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_adi.getSelectedItem().equals("DÜZKÖY")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("ÇAYIRBAĞI");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_adi.getSelectedItem().equals("DÜZKÖY")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("ÇAYIRBAĞI");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_adi.getSelectedItem().equals("FATİH")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("BEŞİRLİ");
            sube_adi.addItem("ÇATAK");
            sube_adi.addItem("ERDOĞDU");
            sube_adi.addItem("HÜKÜMET KONAĞI");
            sube_adi.addItem("KARŞIYAKA");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_adi.getSelectedItem().equals("MAÇKA")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("ESİROĞLU");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_adi.getSelectedItem().equals("OF")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("GÜRPINAR");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_adi.getSelectedItem().equals("SÜRMENE")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("ÇAMBURNU");
            sube_adi.addItem("ÇARŞI");
            sube_adi.addItem("KÖPRÜBAŞI");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_adi.getSelectedItem().equals("TONYA")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("İSKENDERLİ");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_adi.getSelectedItem().equals("TRABZON")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("ÇAĞLAYAN");
            sube_adi.addItem("ÇUKURÇAYIR");
            sube_adi.addItem("DEĞİRMENDERE");
            sube_adi.addItem("K.T.Ü");
            sube_adi.addItem("ORTAHİSAR KAYMAKAMLIĞI");
            sube_adi.addItem("PARK");
            sube_adi.addItem("PELİTLİ");
            //////////////////////////////////////////////////////////////////////////////// 
        } else if (merkez_adi.getSelectedItem().equals("YOMRA")) {
            sube_adi.removeAllItems();
            sube_adi.addItem("");
            sube_adi.addItem("ADLİYE SARAYI");
            sube_adi.addItem("KAŞÜSTÜ");
        }
        //////////////////////////////////////////////////////////////////////////////// 

    }//GEN-LAST:event_merkez_adiActionPerformed

    private void arıza_aciklamasi_yazılımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arıza_aciklamasi_yazılımActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arıza_aciklamasi_yazılımActionPerformed

    private void Ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ekle_buttonActionPerformed
        String insertQuery = "INSERT INTO Yazılım(Merkez_Adı,Şube_Adı,Müdahale_Edilen_Program,Bildirim_Sicili,Arıza_Açıklaması,Arıza_Tarihi) values(?,?,?,?,?,?::date)";
        try {

            prepared = connect.prepareStatement(insertQuery);

            prepared.setString(1, merkez_adi.getSelectedItem().toString());
            prepared.setString(2, sube_adi.getSelectedItem().toString());
            prepared.setString(3, müdahale_edilen_program.getText());
            prepared.setInt(4, Integer.parseInt(bildirim_sicili_giris_yazılım.getText()));
            prepared.setString(5, arıza_aciklamasi_yazılım.getText());
            prepared.setString(6, ariza_tarihi_yazılım.getText());

            if (müdahale_edilen_program.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Müdahale edilen program alanı boş bırakılamaz.");
                return;
            } else if (bildirim_sicili_giris_yazılım.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Bildirim sicili alanı boş bırakılamaz.");
                return;
            } else if (arıza_aciklamasi_yazılım.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Arıza açıklaması boş bırakılamaz.");
                return;
            }

            prepared.execute();

            JOptionPane.showMessageDialog(null, "Veritabanına başarıyla eklendi.");

            updateTable();

        }  catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }


    }//GEN-LAST:event_Ekle_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed

        dispose();
        HomePage homepage = new HomePage();
        homepage.show();


    }//GEN-LAST:event_back_buttonActionPerformed

    private void Kaldır_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kaldır_buttonActionPerformed
        if (!table2.getSelectionModel().isSelectionEmpty()) {
            int row = table2.getSelectedRow();
            String cell = table2.getModel().getValueAt(row, 3).toString();
            String sql = "Delete FROM yazılım where bildirim_sicili = " + cell;

            try {

                prepared = connect.prepareStatement(sql);
                prepared.execute();

                JOptionPane.showMessageDialog(null, "Başarıyla silindi.");
                updateTable();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kaldırmak için bir kolon seçin.");
        }
    }//GEN-LAST:event_Kaldır_buttonActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked

        /*int number = table2.getSelectedRow();
     
       merkez_adi.setSelectedItem(table2.getValueAt(number, 0).toString());
       sube_adi.setSelectedItem(table2.getValueAt(number, 1).toString());
       müdahale_edilen_program.setText(table2.getValueAt(number, 2).toString());
       bildirim_sicili_giris_yazılım.setText(table2.getValueAt(number, 3).toString());
       secer_button.setSelectedItem(table2.getValueAt(number, 3).toString());
       arıza_aciklamasi_yazılım.setText(table2.getValueAt(number, 4).toString());
       ariza_tarihi_yazılım.setText(table2.getValueAt(number, 5).toString());
       
         */
        int row = table2.getSelectedRow();
        String cell = table2.getModel().getValueAt(row, 3).toString();
        String sql = "select * FROM yazılım where bildirim_sicili =" + cell;
        try {

            prepared = connect.prepareStatement(sql);
            resultSet = prepared.executeQuery();
            if (resultSet.next()) {
                jComboBox1.setSelectedItem(resultSet.getString("bildirim_sicili"));
                merkez_adi.setSelectedItem(resultSet.getString("merkez_adı"));
                sube_adi.setSelectedItem(resultSet.getString("Şube_adı"));
                müdahale_edilen_program.setText(resultSet.getString("müdahale_edilen_program"));
                bildirim_sicili_giris_yazılım.setText(resultSet.getString("bildirim_sicili"));
                arıza_aciklamasi_yazılım.setText(resultSet.getString("arıza_açıklaması"));
                ariza_tarihi_yazılım.setText(resultSet.getString("arıza_tarihi"));

            }
            updateCombobox();

        }  catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_table2MouseClicked

    private void elle_degistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elle_degistirActionPerformed
        DateFormat onlyDate = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        ariza_tarihi_yazılım.setText(onlyDate.format(date));
        ariza_tarihi_yazılım.setText(ariza_tarihi_yazılım.getText());
        ariza_tarihi_yazılım.setEditable(true);
        ariza_tarihi_yazılım.setBackground(Color.white);
    }//GEN-LAST:event_elle_degistirActionPerformed

    private void güncelle_buttonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_güncelle_buttonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_güncelle_buttonAncestorAdded

    private void güncelle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelle_buttonActionPerformed

        try {

            if (table2.getSelectedRowCount() == 1) {
                //if single row is selected then update
                String updateQuery = "Update Yazılım set "
                        + " merkez_adı = '" + merkez_adi.getSelectedItem() + "',"
                        + " Şube_adı = '" + sube_adi.getSelectedItem() + "',"
                        + " müdahale_edilen_program = '" + müdahale_edilen_program.getText() + "',"
                        + " bildirim_sicili = '" + bildirim_sicili_giris_yazılım.getText() + "',"
                        + " arıza_açıklaması = '" + arıza_aciklamasi_yazılım.getText() + "',"
                        + " arıza_tarihi = '" + ariza_tarihi_yazılım.getText() + "'"
                        + " where bildirim_sicili = " + jComboBox1.getSelectedItem().toString();

                prepared = connect.prepareStatement(updateQuery);
                prepared.execute();
                JOptionPane.showMessageDialog(this, "Başarıyla güncellendi.");
                updateTable();
                updateCombobox();

            } else {
                if (table2.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "Tablo boş.");
                } else {
                    JOptionPane.showMessageDialog(this, "Lütfen sadece bir tane veri seçin..");
                }
                connect.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }


    }//GEN-LAST:event_güncelle_buttonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox1.setEnabled(false);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void search_hardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_hardwareActionPerformed

        try {

            String sql = "select * from yazılım where müdahale_edilen_program = ?";

            prepared = connect.prepareStatement(sql);
            prepared.setString(1, jTextField1.getText());

            resultSet = prepared.executeQuery();

            table2.setModel(DbUtils.resultSetToTableModel(resultSet));
            if (resultSet.next()) {

                jComboBox1.setSelectedItem(resultSet.getString("bildirim_sicili"));
                merkez_adi.setSelectedItem(resultSet.getString("merkez_adı"));
                sube_adi.setSelectedItem(resultSet.getString("Şube_adı"));
                müdahale_edilen_program.setText(resultSet.getString("müdahale_edilen_program"));
                bildirim_sicili_giris_yazılım.setText(resultSet.getString("bildirim_sicili"));
                arıza_aciklamasi_yazılım.setText(resultSet.getString("arıza_açıklaması"));
                ariza_tarihi_yazılım.setText(resultSet.getString("arıza_tarihi"));

            }
            if (jTextField1.getText().isEmpty()) {
                updateTable();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        updateCombobox();

    }//GEN-LAST:event_search_hardwareActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bildirim_sicili_giris_yazılımKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bildirim_sicili_giris_yazılımKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE) {
            getToolkit().beep();
            evt.consume();
        }


    }//GEN-LAST:event_bildirim_sicili_giris_yazılımKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Software().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ekle_button;
    private javax.swing.JButton Kaldır_button;
    private javax.swing.JTextField ariza_tarihi_yazılım;
    private javax.swing.JTextField arıza_aciklamasi_yazılım;
    private javax.swing.JButton back_button;
    private javax.swing.JTextField bildirim_sicili_giris_yazılım;
    private javax.swing.JButton elle_degistir;
    private javax.swing.JButton güncelle_button;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> merkez_adi;
    private javax.swing.JTextField müdahale_edilen_program;
    private javax.swing.JButton search_hardware;
    private javax.swing.JLabel software_merkez_adı_bilgi;
    private javax.swing.JComboBox<String> sube_adi;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
